### ISSUE TITLE
Possible replay attack in ANTv2 on hardfork

### ISSUE THREAD

**Issue by eduadiez** [aragon/aragon-network-token#23]
In https://github.com/aragon/aragon-network-token/blob/master/packages/v2/contracts/ANTv2.sol since the `chainId` is computed during the constructor, in case of a hardfork this token has the risk of a replay attack.

**Comment by eduadiez** [comment]
I just made a PR #24 with our approach to solve this situation. As you mention this implementation is more efficient in gas consumption

**Comment by sohkai** [comment]
Fixed by #24 :).
