### ISSUE TITLE
Transfer to `0x0` and burn tokens emit the same event

### ISSUE THREAD

**Issue by eduadiez** [aragon/aragon-network-token#25]
Since the smart-contract doesn't avoid transfers to the `0x0` address, this emits the same event that when you call the `burn` function. 

Maybe this's the desired behavior, but if you prevent the user to send tokens to `0x0` you can easily distinguish when the tokens are burned: `emit Transfer(from, address(0), value)`. If he doesn't want the tokens to be burned but he wants the tokens locked he can always send them to `0xdEad000000000000000000000000000000000000` or any other similar address.

Due to this, we changed this line https://github.com/aragon/aragon-network-token/blob/319dbfd1b1b1b8b0382b0e20b87ef2339c2a0c65/packages/v2/contracts/ANTv2.sol#L96
```
require(to != address(this) && to != address(0), "ANTV2:RECEIVER_IS_TOKEN_OR_0");
```

**Comment by sohkai** [comment]
Fixed in #26.
