### ISSUE TITLE
Some bug or very smart logic

### ISSUE THREAD

**Issue by logvik** [aragon/aragon-network-token#9]
Hi, just noticed a part of your code
```
// Aragon Dev owns 30% of the total number of emitted tokens at the end of the sale.
    uint256 aragonTokens = token.totalSupply() * 3 / 7;
```
here declaration with 30%, but below 3/7, I have checked in Remix, I thought some bug, but not, the same result as in the real life -

```
pragma solidity ^0.4.13;

contract MyContract {
  event Print(string _name, uint _value);
  function Test() public returns (bool) {
    uint Tokens = 1000000000000000;
    Print ("Result - ", Tokens * 3 / 9);
    return true;
  }
}
```
Print[
  "Result - ",
  "333333333333333"
]

Result of checking    |  Your code
-----------------------|-------------
1000000000000000  | 1000000000000000
333333333333333    | 428571428571428
~30%                        | ~43%

Also, I thought about presale - there also you have issued tokens, up to 15% with 1M cap. 15% for Dev from WP, in sum = 30, then what does it mean 43% before close?

**Comment by izqui** [comment]
The reason why we multiplied the amount of issued tokens times `3 / 7` is because we needed Aragon's part (15% devs + 15% foundation) to be the 30% of the *total issued amount*.

So we had `x` tokens issued and `y` tokens needed to be created such that `y` was the 30% of `x + y`.

```
(3 / 7) / ((3 + 7) / 7) = 0.3
```

**Comment by izqui** [comment]
Also you can see how it worked in practice: https://etherscan.io/tx/0x566bac5f19caa7ab40db9b6bc1a592748e264a43cf8b7ef07a665e6a0e1141ee

11,882,857.14 ANT were minted which are exactly 30% of the total supply of 39,609,523.80 ANT

**Comment by logvik** [comment]
Oh, ok, confirmed, because totalSupply = only 70% at the time of closing... sorry for disturbing you...

**Comment by izqui** [comment]
No problem!
